"""Snapshot-report freshness (ADR 0021).

`registry/reports/` holds two classes of generated file (see
`cankar/core/reports.py`):

- `snapshot=False` - regenerated byte-identically in CI from committed inputs.
  CI already guards these (`cankar corpus report --all && git diff --exit-code`).
  This module must not touch them.
- `snapshot=True` - computed from gitignored `data/`. CI can never rebuild them,
  so they drifted twice unnoticed: `token-stats.md` and `tokenizer-eval.md` both
  carried a pre-ADR-0014 corpus sha long after the re-merge.

Four of the snapshot reports already stamp the corpus sha they were built from.
Comparing that stamp against the corpus on disk costs one sha256 (~0.3s over
503MB) and catches exactly the drift that happened. This is a LOCAL gate: it
skips when the corpus is absent, which is the normal state in CI and in a fresh
clone.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from cankar.core.manifest import sha256_of
from cankar.core.paths import merged_shard, repo_root
from cankar.core.reports import ReportFreshness, read_stamp

# Corpus-derived snapshot reports that do NOT stamp a sha yet. Pinned so a NEW
# unstamped report cannot be added quietly - extending this set is a conscious
# act. Stamping them is deliberate future work (ADR 0021 "out of scope"), not an
# oversight.
UNSTAMPED_ALLOWLIST = frozenset(
    {
        "corpus-quality.md",
        "merge.md",
        "near-duplicates.md",
    }
)

# Reports that are not built from the merged corpus at all, so a corpus-sha
# stamp would be meaningless. Permanently out of scope, not a TODO.
NOT_CORPUS_DERIVED = frozenset(
    {
        "README.md",  # the governed-dir contract (ADR 0007), not a report
        "dlib-reconcile.md",  # dLib metadata reconciliation
        "style.md",  # the trained style classifier
        "collisions.md",  # snapshot=False, drift-checked in CI
    }
)


def _snapshot_reports() -> list[Path]:
    reports_dir = repo_root() / "registry" / "reports"
    return sorted(
        p
        for p in reports_dir.glob("*.md")
        if p.name not in NOT_CORPUS_DERIVED and not p.name.startswith("coverage-")
    )


def test_stamped_reports_match_the_corpus_on_disk() -> None:
    """No snapshot report may claim a corpus sha other than the live one."""
    corpus = merged_shard()
    if not corpus.exists():
        pytest.skip("merged corpus absent (CI / fresh clone) - freshness is a local gate")

    current = sha256_of(corpus)
    stale = [
        stamp
        for report in _snapshot_reports()
        if (stamp := read_stamp(report, current)).freshness is ReportFreshness.STALE
    ]

    assert not stale, "reports generated from a stale corpus (current {}):\n{}".format(
        current[:12], "\n".join(s.describe() for s in stale)
    )


def test_unstamped_reports_are_the_known_set() -> None:
    """A new corpus-derived report must stamp its sha, or be added here on purpose."""
    corpus = merged_shard()
    if not corpus.exists():
        pytest.skip("merged corpus absent (CI / fresh clone) - freshness is a local gate")

    current = sha256_of(corpus)
    unstamped = {
        report.name
        for report in _snapshot_reports()
        if read_stamp(report, current).freshness is ReportFreshness.UNSTAMPED
    }

    assert unstamped == UNSTAMPED_ALLOWLIST, (
        "unstamped corpus-derived reports changed.\n"
        f"  now:      {sorted(unstamped)}\n"
        f"  expected: {sorted(UNSTAMPED_ALLOWLIST)}\n"
        "A new report here means it silently escapes the freshness gate - stamp "
        "the corpus sha in its writer, or widen UNSTAMPED_ALLOWLIST deliberately."
    )
