"""Generated-report contract - one place defines the marker and write shape.

Two classes of file live in registry/reports/ (the README there is the
governed-dir contract, ADR 0007):

- drift-checked: regenerated byte-identically in CI from committed inputs
  (coverage, collisions) - `cankar corpus report --all && git diff`
- snapshot: computed from gitignored data/, regeneration is manual
  (quality, near-duplicates) - CI cannot rebuild these; do NOT fold them
  into `report --all` or the drift gate goes red in CI

The marker line encodes which class a report is; four writers share this
shape (rule of three, design-review 2026-07).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

# Header region searched for the corpus stamp. Four writers phrase it four ways
# (`Corpus sha256 \`x\``, `... corpus.jsonl\` sha256 \`x\``, and chunk.py puts the
# sha on the FOLLOWING line), so this spans newlines after `sha256` on purpose.
# Anchored on "corpus" so a report stamping some other artifact's sha - the style
# classifier, the dLib reconcile - is never mistaken for a corpus-derived one.
_HEADER_LINES = 20
_CORPUS_SHA_RE = re.compile(r"corpus[^\n]{0,80}sha256[\s`]*([a-f0-9]{64})", re.IGNORECASE)
_GENERATED_BY_RE = re.compile(r"GENERATED by `([^`]+)`")


class ReportFreshness(StrEnum):
    """Whether a report's stamped corpus sha still matches the corpus on disk."""

    FRESH = "fresh"
    STALE = "stale"
    UNSTAMPED = "unstamped"  # carries no corpus sha - this gate cannot judge it


@dataclass(frozen=True)
class ReportStamp:
    """One report's provenance stamp, as read off its header."""

    name: str
    freshness: ReportFreshness
    stamped_sha: str | None
    command: str | None  # regeneration command, from the GENERATED marker

    def describe(self) -> str:
        cmd = f"  regenerate: {self.command}" if self.command else ""
        return f"{self.name}: stamped {self.stamped_sha or '-'}{cmd}"


def generated_marker(command: str, *, snapshot: bool) -> str:
    tail = "snapshot over gitignored data" if snapshot else "do not edit by hand"
    return f"<!-- GENERATED by `{command}` - {tail} -->"


def write_report(out: Path, lines: list[str]) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")


def read_stamp(report: Path, current_corpus_sha: str) -> ReportStamp:
    """Classify one report against the corpus sha currently on disk.

    A malformed or truncated sha simply fails to match the 64-hex pattern and
    lands in UNSTAMPED, which the freshness test treats as a tracked gap rather
    than a silent pass - never as FRESH.
    """
    header = "\n".join(report.read_text(encoding="utf-8").splitlines()[:_HEADER_LINES])
    command_match = _GENERATED_BY_RE.search(header)
    command = command_match.group(1) if command_match else None

    sha_match = _CORPUS_SHA_RE.search(header)
    if sha_match is None:
        return ReportStamp(report.name, ReportFreshness.UNSTAMPED, None, command)

    stamped = sha_match.group(1)
    freshness = ReportFreshness.FRESH if stamped == current_corpus_sha else ReportFreshness.STALE
    return ReportStamp(report.name, freshness, stamped, command)
