"""Generated-report contract - one place defines the marker and write shape.

Two classes of file live in registry/reports/ (the README there is the
governed-dir contract, ADR 0007):

- drift-checked: regenerated byte-identically in CI from committed inputs
  (coverage, collisions) - `cankar corpus report --all && git diff`
- snapshot: computed from gitignored data/, regeneration is manual
  (quality, near-duplicates) - CI cannot rebuild these; do NOT fold them
  into `report --all` or the drift gate goes red in CI

The marker line encodes which class a report is; four writers share this
shape (rule of three, design-review 2026-07).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

# Header region searched for the corpus stamp. Four writers phrase it four ways
# (`Corpus sha256 \`x\``, `... corpus.jsonl\` sha256 \`x\``, and chunk.py puts the
# sha on the FOLLOWING line), so this spans newlines after `sha256` on purpose.
# Anchored on "corpus" + `sha256` on ONE line so a report stamping some other
# artifact's sha - the style classifier, the dLib reconcile - is never mistaken
# for a corpus-derived one, and so `merge.md` / `corpus-quality.md` (whose
# GENERATED command contains the word "corpus") read as unstamped.
# IGNORECASE covers the label only; the hex is lowercased before comparison so an
# uppercase stamp reads as FRESH rather than as a spurious STALE.
_HEADER_LINES = 20
_CORPUS_SHA_RE = re.compile(r"corpus[^\n]{0,80}sha256[\s`]*([a-fA-F0-9]{64})", re.IGNORECASE)
_GENERATED_BY_RE = re.compile(r"GENERATED by `([^`]+)`")
_SNAPSHOT_TAIL = "snapshot over gitignored data"


class ReportFreshness(StrEnum):
    """Whether a report's stamped corpus sha still matches the corpus on disk."""

    FRESH = "fresh"
    STALE = "stale"
    UNSTAMPED = "unstamped"  # carries no corpus sha - freshness cannot be judged


@dataclass(frozen=True)
class ReportStamp:
    """One report's provenance, read off its header. Parsing only - no policy.

    Deliberately independent of the current corpus: whether a report is stamped
    at all is a property of the file, so the pinning test that guards against new
    unstamped reports runs in CI, where no corpus exists. Only `freshness()`
    needs the live sha.
    """

    name: str
    corpus_sha: str | None  # None == unstamped
    command: str | None  # regeneration command, from the GENERATED marker
    snapshot: bool  # marker tail: snapshot over gitignored data vs committed input

    def freshness(self, current_corpus_sha: str) -> ReportFreshness:
        if self.corpus_sha is None:
            return ReportFreshness.UNSTAMPED
        if self.corpus_sha == current_corpus_sha.lower():
            return ReportFreshness.FRESH
        return ReportFreshness.STALE

    def describe(self, current_corpus_sha: str) -> str:
        cmd = f" - regenerate: {self.command}" if self.command else ""
        return (
            f"{self.name}: {self.freshness(current_corpus_sha)} "
            f"(stamped {(self.corpus_sha or '-')[:12]}, corpus {current_corpus_sha[:12]}){cmd}"
        )


def generated_marker(command: str, *, snapshot: bool) -> str:
    tail = _SNAPSHOT_TAIL if snapshot else "do not edit by hand"
    return f"<!-- GENERATED by `{command}` - {tail} -->"


def write_report(out: Path, lines: list[str]) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")


def parse_stamp(report: Path) -> ReportStamp:
    """Read one report's provenance header.

    A malformed or truncated sha fails the 64-hex match and reads as unstamped,
    which the freshness tests treat as a tracked gap - never as fresh.
    """
    header = "\n".join(report.read_text(encoding="utf-8").splitlines()[:_HEADER_LINES])
    command_match = _GENERATED_BY_RE.search(header)
    sha_match = _CORPUS_SHA_RE.search(header)
    return ReportStamp(
        name=report.name,
        corpus_sha=sha_match.group(1).lower() if sha_match else None,
        command=command_match.group(1) if command_match else None,
        snapshot=_SNAPSHOT_TAIL in header,
    )
